
<?php 

if(count($block->getQuestion()) != 0) {
	foreach($this->getQuestion() as $ky) {
	  $qid=$ky->getQuestionId();
	}
}
$customer_id=$block->getCustomer()->getId();
$getinfo = $block->getQuestion();
$proinfo = $block->getProduct();

?>
<div class="wk-mp-design block" id="wk-bodymain">
	<div class="block-title">
	<span><?php echo __('Buyer Question') ?></span>
	<button class="button wk-mp-btn btn" title="<?php echo __('Submit') ?>" type="button" data-id="<?php echo $getinfo->getQuestionId(); ?>">
		<span><span><?php echo __('Submit') ?></span></span>
	</button>
	</div>
	<div class="question">	
			<strong><span><h4><?php echo __('Question') ?></h4></span></strong>
	
		<div class ="fieldset wk_mp_fieldset"> 
		 	<div>
		  		<div class='pimg'>
		  			<a href='<?php echo $proinfo->getProductUrl(); ?>' target="_blank" class='hrefa' > <img src="<?php echo $block->imageHelperObj()->init($proinfo, 'product_page_image_medium')->getUrl();?>"  class="wk_mpqa_image" /> </a>
		   		</div> 
		 		<div class='pinfo'> 
		 			<?php $procontent = strlen($proinfo->getDescription())>27?substr($proinfo->getDescription(),0,27)."..":$proinfo->getDescription(); ?>
		 			<div> 
		 				<label class="plabl"><?php echo __('Product Name:') ?></label> 
		 				<a href='<?php echo $proinfo->getProductUrl(); ?>' target="_blank" class='hrefa' >
		 					<label class="nlabl"> <?php echo $proinfo->getName(); ?> </label> 
		 				</a>  
		 			</div>  
		 			<div> 
		 				<label class="plabl"><?php echo __('Product Description:') ?></label> 
		 				<span class="wk_desc"><?php echo $proinfo->getDescription(); ?> </span> 
		 			</div>
		 		</div>
		 	</div>
		 	<div class='clr'></div>     	     
		   		<div class='mainquest1' >
		   			<div class='respond' id='<?php echo $getinfo->getQuestionId(); ?>'>
		       			<div> 
		       				
		       					<label id='mlabl'> Buyer:</label> 
		       				 
		       				<strong><?php echo $getinfo->getSubject();?></strong> 
		       			</div>
		       			<div class='conten'>
		       				<span class="wk_prewrap"><?php echo $getinfo->getContent(); ?>
					       </span>
					    </div>
		       			<div class='dt'>
		       				<!-- date -->
		       			</div>
		         	<div>
		          		<div class='txtcomment1'>
							<div class='margres'> 
								<textarea id='maincont' class="txtsize mpqatext" style="width:100%"></textarea> 
							</div>
		          		</div>
		         	</div>
		        </div> 
			     <!-- old answers -->
			     <?php
			     $answers=$block->getAnswers();
			     // print_r($answers->getData());	die;
			     foreach ($answers as $key) {
			     	
			     ?>
			     <div class='respond newres' id=''>
		       		
		       		<div>
		       		<?php if($key->getRespondType()=='Customer'){
		       			$cname=$block->getCustomerById($key->getRespondFrom())->getName();
		       			?>
		       			<label class='rlabl' style="font-weight: bold;"><?php echo __('Customer').'('.$cname.')'; ?></label> 
		       		<?php
		       		}else{	?>
		       			<label class='rlabl' style="font-weight: bold;"><?php echo $key->getRespondType(); ?></label> 
		       		<?php } ?>
		       		</div>
		       		<div class='conten '><span class="wk_prewrap"><?php echo $key->getContent(); ?></span>
		       		</div>
		        	<div class='dte'>
						
		       				<?php echo $block->formatDate($key->getCreatedAt(),IntlDateFormatter::MEDIUM,true);  ?>
		       		</div> 
		       	</div>
		       	<?php 
		       	}
		       	?> 
			     <!-- old -->
		    </div>
		    
		</div>
	</div>
</div>

<?php
$formData = [
    'submitanswer_url'=> $block->getUrl("mpqa/mpqaquest/saveanswer", ["_secure" => $this->getRequest()->isSecure()]),
    'question_id' => $getinfo->getQuestionId(),
    'customer_id'   => $customer_id
];
$serializedFormData = $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($formData);
?>
<script type="text/x-magento-init">
    {
        "*": {
            "giveanswer": <?php  echo $serializedFormData; ?>
        }
    }
</script>