<?php
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Mpqa
 * @author    Webkul
 * @copyright Copyright (c) 2010-2017 Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

// @codingStandardsIgnoreFile
$_helper = $this->helper('Webkul\Marketplace\Helper\Data');
$isPartner= $_helper->isSeller();
$magentoCurrentUrl = $block->getCurrentUrl();
$isSellerGroup = $_helper->isSellerGroupModuleInstalled();
?>
<?php 
if($isPartner){ 
    if(($isSellerGroup && $_helper->isAllowedAction('mpqa/mpqaquest/showquestions')) || !$isSellerGroup) { ?>
        <li class="nav item <?php echo strpos($magentoCurrentUrl,'mpqa/mpqaquest/showquestions')? "current":"";?>">     
            <?php if(strpos($magentoCurrentUrl,'mpqa/mpqaquest/')!== false){ ?>   
                <strong><?php /* @escapeNotVerified */ echo __('Manage MPQA') ?></strong>        
            <?php 
            } else{ ?>    
                <a href="<?php echo $block->getUrl('mpqa/mpqaquest/showquestions', ['_secure' => $this->getRequest()->isSecure()]); ?>">
                    <?php /* @escapeNotVerified */ echo __('Manage MPQA') ?>
                </a>                
            <?php 
            } ?>      
        </li>
<?php }
} ?>
