<?php

/**
 * Webkul_Auction View On Category.
 * @category  Webkul
 * @package   Webkul_Auction
 * @author    Webkul
 * @copyright Copyright (c) 2010-2017 Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

?>
<script type="text/x-magento-init">
    {
        "body": {
             "viewoncategory": 
                    {
                        "buyItNow": "<?php echo __('Buy it now')?>",
                        "viewDetail" : "<?php echo __('View Detail') ?>"
                    }
        }
    }
</script>
