<?php 
/**
 * Webkul Software.
 *
 * @category  Webkul
 * @package   Webkul_Mpqa
 * @author    Webkul
 * @copyright Copyright (c) 2010-2017 Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */
if(count($block->getQuestion()) != 0) {
	foreach($this->getQuestion() as $ky) {
	  $qid=$ky->getQuestionId();
	}
}
$getinfo = $block->getQuestion();
$proinfo = $block->getProduct();

?>

<div class="wk-mp-design block" id="wk-bodymain">
	<div class="question">	
			<strong><span><h4><?php echo __('Question') ?></h4></span></strong>
	
		<div class ="fieldset wk_mp_fieldset"> 
		 	<div>
		  		<div class='pimg'>
		  			<a href='<?php echo $proinfo->getProductUrl(); ?>' target="_blank" class='hrefa' > <img src="<?php echo $block->imageHelperObj()->init($proinfo, 'product_listing_thumbnail_preview')->getUrl();?>"  class="image" /> </a>
		   		</div> 
		 		<div class='pinfo'> 
		 			<?php $procontent = strlen($proinfo->getDescription())>27?substr($proinfo->getDescription(),0,27)."..":$proinfo->getDescription(); ?>
		 			<div> 
		 				<label class="plabl"><?php echo __('Product Name:') ?></label> 
		 				<a href='<?php echo $proinfo->getProductUrl(); ?>' target="_blank" class='hrefa' >
		 					<label class="nlabl"> <?php echo $proinfo->getName(); ?> </label> 
		 				</a>  
		 			</div>  
		 			<div> 
		 				<label class="plabl"><?php echo __('Product Description:') ?></label> 
		 				<span class="nlabl"><?php echo $proinfo->getDescription(); ?> </span> 
		 			</div>
		 		</div>
		 	</div>
		 	<div class='clr'></div>     	     
		   		<div class='mainquest1' >
		   			<div class='respond' id='<?php echo $getinfo->getQuestionId(); ?>'>
		       			<div> 
		       				
		       					<label id='mlabl'><?php echo $getinfo->getQaNickname().'(Buyer):'?></label> 
		       				
		       				<strong><?php echo $getinfo->getSubject();?></strong> 
		       			</div>
		       			<div class='conten'><span class="wk_prewrap"><?php echo $getinfo->getContent(); ?>
					       </span>
					    </div>
		       			<div class='dt'>
		       				<!-- date -->
		       				<span>
			       				<?php 
							      echo $block->formatDate($getinfo->getCreatedAt(),\IntlDateFormatter::MEDIUM,true);
							       
						        ?>
					       </span>
		       			</div>
		         	<div>
		          		<div class='txtcomment1'>
							<div class='margres'> 
								<textarea id='maincont' class="txtsize mpqatext" style="width:100%"></textarea> 
							</div>
		          		</div>
		         	</div>
		         	<button class="button wk-mp-btn btn" title="<?php echo __('Submit') ?>" type="button" data-id="<?php echo $getinfo->getQuestionId(); ?>">
						<span><span><?php echo __('Submit') ?></span></span>
					</button>
					 <div class='clr'></div>  
		        </div> 
		       
			     <!-- old answers --><?php
			     $answers=$block->getAnswers();
			    
			     foreach ($answers as $key) {
			     	
			     ?>
			     <div class='respond newres' id=''>
		       		<div class='marrem'> 
		       			<button class='delet wk-button' id='<?php echo $key->getAnswerId();?>'>
						   <span class='delet'>X</span> 
						</button>
		       		</div> 
		       		
		       		<div>
		       			<label class='rlabl' style="font-weight: bold;"><?php if($key->getRespondType()=='Admin') echo $key->getRespondType(); elseif ($key->getRespondType()=='Seller') echo $key->getRespondType(); else {echo $key->getRespondNickname().'('.$key->getRespondType().')';} ?></label> 
		       		</div>
		       		<div class='conten'><span class="wk_prewrap"><?php echo $key->getContent(); ?> </span>
		       		</div>
		        	<div class='dte'>
		       				<?php echo $block->formatDate($key->getCreatedAt(),\IntlDateFormatter::MEDIUM,true);  ?>
		       		</div> 
		       	</div>
		       	<?php 
		       	}
		       	?> 
			     <!-- old -->
		    </div>
		    
		</div>
	</div>
</div>
<?php
$formData = [
    'submitanswer_url'=> $block->getUrl("mpqa/mpqa/giveanswer", ["_secure" => $this->getRequest()->isSecure()]),
    'delete_url' => $block->getUrl("mpqa/mpqa/deleteanswer", ["_secure" => $this->getRequest()->isSecure()]),
    'question_id' => $getinfo->getQuestionId()
];
$serializedFormData = $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode($formData);
?>
<script type="text/x-magento-init">
    {
        "*": {
            "giveanswer": <?php  echo $serializedFormData; ?>
        }
    }
</script>