<?php
/**
  * Webkul_MpAuction deal list block.
  * @category  Webkul
  * @package   Webkul_MpAuction
  * @author    Webkul
  * @copyright Copyright (c) 2010-2017 Webkul Software Private Limited (https://webkul.com)
  * @license   https://store.webkul.com/license.html
  */

// @codingStandardsIgnoreFile

/** @var $block \Webkul\Marketplace\Block\Product\Productlist */

$helper = $this->helper('Webkul\Marketplace\Helper\Data');
$paramData = $this->getRequest()->getParams();
$filter = '';

if (isset($paramData['s'])) {
    $filter = $paramData['s'] != '' ? $paramData['s'] : '';
}
$auctionTimeOffset = [];
$_products_coll = $block->getAllProducts(); 
if ($helper->isSeller() && $block->isAuctionEnable()) { ?>
<div class="wk-mp-design">
	<fieldset class="fieldset info wk-mp-fieldset">
		<legend class="legend">
			<span><?php /* @escapeNotVerified */ echo __('My Auction Product List') ?></span>
		</legend>
		<div class="grid">
			<div class="hor-scroll">
				<form action="<?php /* @escapeNotVerified */ echo $block->getUrl('mpauction/account/auctionlist/', ['_secure' => $this->getRequest()->isSecure()])?>" method="get" id="form-productlist-filter"  name="formProductlistFilter" data-mage-init='{"validation":{}}'>
					<table cellspacing="0" class="border wk-mp-list-table">
					    <thead>
					        <tr id="wk-mp-tr-heading">
					            <th><span><?php /* @escapeNotVerified */ echo __('Product Name') ?></span></th>
					            <th><span>&nbsp;</span></th>
					        </tr>
					    </thead>
					    <tbody class="wk-mp-body">
					    	<tr>
					    		<td>
					    			<input type="text" class="input-text" name="s" placeholder='<?php /* @escapeNotVerified */ echo __('Search by product name') ?>' value="<?php /* @escapeNotVerified */ echo $filter?>"/>
					    		</td>
					    		<td>
					    			<button class="button" title="Save" type="submit">
										<span><span><span><?php /* @escapeNotVerified */ echo __('Submit') ?></span></span></span>
									</button>
					    		</td>
					    	</tr>
					    </tbody>
					</table>
				</form>
				<?php if ($_products_coll && count($_products_coll)): ?>
					<form action="<?php echo $block->getUrl('mpauction/account/massdisable', ['_secure' => $this->getRequest()->isSecure()]) ?>" method="post" id="form-productlist-massdisable" name="formProductlistMassDisable" data-mage-init='{"validation":{}}' class="table-wrapper">
						<?php echo $block->getBlockHtml('formkey')?>
						<?php echo $block->getBlockHtml('seller.formkey')?>
						<button class="button" title="<?php /* @escapeNotVerified */ echo __('Cancel Auction') ?>" type="submit" id="mass-delete-butn">
							<span>
								<span><?php /* @escapeNotVerified */ echo __('Cancel Auction') ?></span>
							</span>
						</button>
						<table cellspacing="0" class="table data border wk-mp-list-table wk-mp-list-container-table">
						    <thead>
						        <tr class="wk-content">
						        	<th class="wk-check-first-td">
						    			<span>
											<input type="checkbox" name="mpselecctall" value="all" id="mpauctionselecctall"/>
										</span>
						    		</th>
						    		<th class="wk-first-td name">
						    			<span class="label">
											<?php /* @escapeNotVerified */ echo __('Auction Product')?>
										</span>
						    		</th>
						    		<th class="wk-first-td qty">
						    			<span class="label">
											<?php /* @escapeNotVerified */ echo __('Quantity')?>
										</span>
						    		</th>
						    		<th class="wk-first-td">
						    			<span class="label name">
											<?php /* @escapeNotVerified */ echo __('Auction Date')?>
										</span>
						    		</th>
						    		<th class="wk-first-td options">
						    			<span class="label name">
											<?php /* @escapeNotVerified */ echo __('Options')?>
										</span>
						    		</th>
						    		<th class="wk-first-td status">
						    			<span class="label name">
										<?php /* @escapeNotVerified */ echo __('Auction Status')?>
										</span>
						    		</th>
						    		<th class="wk-first-td">
						    			<span class="label name">
										<?php /* @escapeNotVerified */ echo __('Product Sold')?>
										</span>
						    		</th>
						    		<th class="wk-first-td">
						    			<span class="label name">
											<?php /* @escapeNotVerified */ echo __('Bid Detail')?>
										</span>
						    		</th>
						    		<th>
						    			<span class="label">
											<?php /* @escapeNotVerified */ echo __('Action')?>
										</span>
						    		</th>			    		
						    	</tr>
						    </thead>
						    <tbody>
						    	<?php 
						    	$i = 0;
								foreach($_products_coll as $aucDetail){
									$i++;
									$products = $block->getProductDetail($aucDetail->getProductId());
					            	$imageUrl = $block->imageHelperObj()->init($products, 'product_page_image_small')
						                        ->setImageFile($products->getFile())->getUrl();
									?>
							    	<tr class="wk-row-view <?php /* @escapeNotVerified */ echo $class = ($i == count($block->getAllProducts()))? 'wk-last_tr':''?>">
							    		<td data-th="Select" class="col wk-check-first-td">
							    			<span>
												<input type="checkbox" name="auction_mass_disable[]" class="mpcheckbox" value="<?php /* @escapeNotVerified */ echo $aucDetail->getEntityId(); ?>"/>
											</span>
							    		</td>
							    		<td data-th="<?php /* @escapeNotVerified */ echo __('Auction Product') ?>" class="col wk-first_td">
											<input type="hidden" class="hidden-id" value="<?php /* @escapeNotVerified */ echo $products->getEntityId(); ?>" />
											<div class="label name" title="<?php /* @escapeNotVerified */ echo $products->getName(); ?>">
												<div class="wk-pro-divide1">
													<img src="<?php /* @escapeNotVerified */ echo $imageUrl?>" class="image" />
												</div>
												<div class="wk-pro-divide2">
													<div style="width:100%;">
														<?php if($products->getStatus()==1 && $products->getVisibility()!=1) { ?>
															<a href="<?php /* @escapeNotVerified */ echo $products->getProductUrl()?>" target="blank">
														<?php }?>
															<?php /* @escapeNotVerified */ echo $products->getName();?>
														<?php if($products->getStatus()==1 && $products->getVisibility()!=1) { ?>
															</a>
														<?php }?>
													</div>
													<div style="width:100%;float:left;">
														<div style="font-size:10px;">
															<b><?php /* @escapeNotVerified */ echo __('Starting Price :')?></b>
															<?php /* @escapeNotVerified */ echo $block->getFormatedPrice($aucDetail->getStartingPrice(), $helper->getCurrencySymbol());?>
															</div>
														<div style="font-size:10px;">
															<b><?php /* @escapeNotVerified */ echo __('Reserve Price :')?></b>
															<?php /* @escapeNotVerified */ echo $block->getFormatedPrice($aucDetail->getReservePrice(), $helper->getCurrencySymbol());?>
														</div>
													</div>
												</div>
											</div>
							    		</td>
							    		<td data-th="<?php /* @escapeNotVerified */ echo __('Quantity') ?>" class="col">
							    			<div>
							    				<b><?php /* @escapeNotVerified */ echo __('Min : ')?></b>
							    				<?php /* @escapeNotVerified */ echo $aucDetail->getMinQty()?>
						    				</div>
							    			<div>
							    				<b><?php /* @escapeNotVerified */ echo __('Max : ')?></b>
							    				<?php /* @escapeNotVerified */ echo $aucDetail->getMaxQty()?>
							    			</div>
							    		</td>
							    		<td data-th="<?php /* @escapeNotVerified */ echo __('Auction Date') ?>" class="col">
							    			<div><b><?php /* @escapeNotVerified */ echo __('Start :')?></b>
							    				<span id="start_auction_time<?php echo $aucDetail->getEntityId(); ?>"><?php /* @escapeNotVerified */ echo $block->getDateTimeAsLocale($aucDetail->getStartAuctionTime());
												$auctionTimeOffset[$aucDetail->getEntityId()]['start_auction_time'] = $block->getUtcOffset($aucDetail->getStartAuctionTime()); ?></span>
						    				</div>
											<div><b><?php /* @escapeNotVerified */ echo __('Stop :')?></b>
												<span id="stop_auction_time<?php echo $aucDetail->getEntityId(); ?>"><?php /* @escapeNotVerified */ echo $block->getDateTimeAsLocale($aucDetail->getStopAuctionTime());
												$auctionTimeOffset[$aucDetail->getEntityId()]['stop_auction_time'] = $block->getUtcOffset($aucDetail->getStartAuctionTime());
												?></span>
											</div>
										</td>
							    		<td data-th="<?php /* @escapeNotVerified */ echo __('Options') ?>" class="col">
							    			<div>
							    				<b><?php /* @escapeNotVerified */ echo __('Increment :')?></b>
							    				<?php /* @escapeNotVerified */ echo $block->getStatusLabel($aucDetail->getIncrementOpt())?>
						    				</div>
											<div><b><?php /* @escapeNotVerified */ echo __('Auto Bid :')?></b>
												<?php /* @escapeNotVerified */ echo $block->getStatusLabel($aucDetail->getAutoAuctionOpt())?>
											</div>
										</td>
							    		<td data-th="<?php /* @escapeNotVerified */ echo __('Auction Status') ?>" class="col"><?php /* @escapeNotVerified */ echo $block->getAuctionStatusLabel($aucDetail->getAuctionStatus())?></td>
							    		<td data-th="<?php /* @escapeNotVerified */ echo __('Product Sold') ?>" class="col"><?php /* @escapeNotVerified */ echo $block->getAucProSoldStatus($aucDetail->getEntityId())?></td>
							    		<td data-th="<?php /* @escapeNotVerified */ echo __('Bid Detail') ?>" class="col">
							    			<a href="<?php /* @escapeNotVerified */ echo $block->getBidDetailUrl($aucDetail->getEntityId())?>" class="button" ><?php /* @escapeNotVerified */ echo __('View') ?></a>
							    		</td>
							    		<td data-th="<?php /* @escapeNotVerified */ echo __('Action') ?>" class="col">
							    			<a href="<?php /* @escapeNotVerified */ echo $block->getAddAuctionUrl($aucDetail->getEntityId())?>" class="button" ><?php /* @escapeNotVerified */ echo $aucDetail->getAuctionStatus()? __('Edit') : __('Detail') ?></a>
							    		</td>			    		
							    	</tr>
							    	<?php
							    }?>
						    </tbody>
						</table>
					</form>				
				<?php else: ?>
					<div class="wk-emptymsg">
						<?php /* @escapeNotVerified */ echo __('No Product Available') ?>
					</div>
				<?php endif ?>					
			</div>
		</div>
		<?php if ($block->getPagerHtml()): ?>
	        <div class="order-products-toolbar toolbar bottom"><?php /* @escapeNotVerified */ echo $block->getPagerHtml(); ?></div>
	    <?php endif ?>	
	</fieldset>	
	<div class="buttons-set">
		<p class="back-link">
			<a href="javascript:;" onclick="javascript: window.history.back();" class="left">&laquo; <?php /* @escapeNotVerified */ echo __('Back') ?></a>
		</p>
	</div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "sellerauctionlist": {
				"zone": "<?php echo $block->getConfigTimeZone() ?>",
				"timeOffset" : <?php echo json_encode($auctionTimeOffset); ?>
			}
        }
    }
</script>
<?php } else { ?>
<h3><?php /* @escapeNotVerified */ echo __('Add auction not allowed')?></h3>
<?php } ?>