<?php

/**
 * Webkul_MpAuction Detail Page.
 * @category  Webkul
 * @package   Webkul_MpAuction
 * @author    Webkul
 * @copyright Copyright (c) 2010-2017 Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

?>
<?php $auctionDetails = $block->getAuctionDetails(); ?>
<?php echo $block->getChildHtml('info'); ?>
<?php if ($auctionDetails && count($auctionDetails)): ?>
    <div class="table-wrapper ">
        <table class="data table" id="my-auction-bid-table">
            <caption class="table-caption"><?php echo __('Auctions Bid') ?></caption>
            <thead>
                <tr>
                    <th scope="col" class="col"><?php echo __('Product Name') ?></th>
                    <th scope="col" class="col"><?php echo __('Bidding Price') ?></th>
                    <th scope="col" class="col"><?php echo __('Bid Status') ?></th>
                    <th scope="col" class="col"><?php echo __('Winning Status') ?></th>
                    <!--th scope="col" class="col">&nbsp;</th-->
                </tr>
            </thead>
            <tbody>
                <?php foreach ($auctionDetails as $auctionData): ?>
                    <tr>
                        <td data-th="<?php echo $block->escapeHtml(__('Product Name ')) ?>" class="col">
                            <?php $pro = $block->getProductDetail($auctionData->getProductId()); ?>
                            <a href="<?php  echo $pro['url'] ?>" target="_blank" class="action view">
                                <span><?php echo $pro['name'] ?></span>
                            </a>
                        </td>
                        <td data-th="<?php echo $block->escapeHtml(__('Bidding Price')) ?>" class="col">
                            <?php echo $block->formatPrice($auctionData->getAuctionAmount()) ?>
                        </td>
                        <td data-th="<?php echo $block->escapeHtml(__('Bid Status')) ?>" class="col"><?php echo $block->status($auctionData->getStatus()) ?></td>
                        <td data-th="<?php echo $block->escapeHtml(__('Winning Status')) ?>" class="col"><?php echo $block->winningStatus($auctionData) ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
    <?php endif ?>
<?php else: ?>
    <div class="message info empty"><span><?php echo __('You have no bid records.'); ?></span></div>
<?php endif ?>

